decred/dcrstakepool

config.go
controllers/dcrclient.go
controllers/main.go
sample-dcrstakepool.conf
server.go
views/status.html

Fixes #17 and first pass for #28 and partly #11

Add better wallet rpc connection handling

---

controllers/dcrclient.go
controllers/main.go
sample-nginx.conf

An option for getting the "real" client IP into the app via the realip module of nginx.
Also update log_format with "$realip_remote_addr".

Use ngx_http_realip_module and X-Real-IP.

---

server.go
system/core.go
system/sigs.go
system/sigs_unix.go
system/sigs_windows.go

Let it build on Windows, but this disables template reloading on CTRL+C.

Portable ReloadTemplatesSig

---

controllers/main.go

Closes #78.
Should probably also prevent the button from showing but that can be done as part of the big votebits handling rewrite that is coming soon.

return early with 0 tickets so we don't panic in SetTicketsVoteBits()

---

system/core.go

Also bail if Walk or ParseFiles returns non-nill error.
Fixes https://github.com/decred/dcrstakepool/issues/82
With this, instead of a panic, you get:
[CRT] DCRS: Failed to load templates: lstat tplstakepool/views: no such file or directory

Check for invalid path in the WalkFnc.

---

views/footer.html
views/home.html

bump copyright and fix grammar

---

models/user.go
server.go

Addresses https://github.com/decred/dcrstakepool/issues/91
This PR adds some basic error checking and appropriate returns.  However, `models.GetDbMap` should perhaps get and error return value, but it is not clear which if any of the db statements failures are tolerable.
Before:
```
[CRT] MODL: Create tables faileddial tcp [::1]:3306: getsockopt: connection refused
[CRT] MODL: checking whether columnHeightRegistered exists faileddial tcp [::1]:3306: getsockopt: connection refused
[CRT] MODL: adding new column HeightRegistered faileddial tcp [::1]:3306: getsockopt: connection refused
[CRT] MODL: UPDATE Users SET HeightRegistered = 15346 WHERE MultiSigAddress <> '' faileddial tcp [::1]:3306: getsockopt: connection refused
[CRT] MODL: setting HeightRegistered to 0 faileddial tcp [::1]:3306: …
```

Add some basic error checking in db setup.

---

views/passwordreset.html
views/passwordupdate.html
views/tickets.html

Closes #105.
Just some minor things I noticed:
- password reset captcha was dark instead of light like on the other pages
- password update text was probably copied & pasted from the email update
- invalid tickets alert looked ridiculously small
- no live tickets font size didn't match the other no ... tickets size

fix minor inconsistencies/pastos

---

goclean.sh

We're hitting timeouts randomly so bump deadline.

bump deadline

---

views/error.html

add back template definition to error page

---

backend/stakepoold/config.go
config.go
log.go

- enablestakemining -> enablevoting in samepl-dcrwallet.conf
- remove unused functions
- use fileExists API

various cleanups

---

backend/stakepoold/config.go

Add appdata so that we can have a single entry to modify all the config
files and directories.  This code is the same as dcrwallet and dcrd.
Fixes #136

stakepoold: add appdata support.

---

backend/stakepoold/server.go

All other tools print appdata.  Make this consistent.

stakepoold: Forgot to print appdir

---

controllers/main.go
views/voting.html

show selected agenda choice and improve UI a bit

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
backend/stakepoold/server_test.go

start adding a test framework

---

backend/stakepoold/server.go

I misunderstood the reason for the fetch; this fixes that.

stakepoold: fix a misunderstanding on my part

---

controllers/main.go

fix last block invalid votebits validation

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go

Also parallelize all wallet questions in order push work to wallet as
quickly as possible instead of sending message and waiting for an answer
*N times.
Fix ctrl-c to actually exit.

stakepoold: remove wallet fetch from critical path

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go

put voting back into a single loop

---

public/css/styles.css
views/home.html

views: fix signup button markup on main page

---

controllers/main.go
views/status.html

views: revamp status page to fix bugs/visual design

---

controllers/main.go
views/tickets.html

break out expired tickets from missed

---

README.md
config.go
sample-dcrstakepool.conf
sample-stakepoold.conf

Pools are starting to migrate over so we can remove this restriction.

allow stakepoold on mainnet

---

controllers/main.go

show voting status properly

---

backend/stakepoold/config.go
backend/stakepoold/log.go
backend/stakepoold/ntfnhandlers.go
backend/stakepoold/userdata/log.go
config.go
controllers/dcrclient.go
controllers/main.go
goclean.sh

enable ineffassign

---

backend/stakepoold/rpcclient.go

bump requried node and wallet RPC API versions

---

controllers/main.go
system/core.go

throw error code and warn on invalid admin access

---

backend/stakepoold/rpcclient.go
controllers/main.go
glide.lock

~~NOTE: This PR contains a temporary glide redirect to https://github.com/dnldd/dcrd/tree/decodeaddress, https://github.com/dnldd/dcrutil, https://github.com/dnldd/dcrrpcclient/tree/decodeaddress and https://github.com/dnldd/dcrwallet/commit/770c135016b50e96f3bbaa29beeb3f77175165cd. This will need to be removed before merging~~

Update DecodeAddress signature

---

models/user.go

fix hardcoded table name in addColumn

---

backend/stakepoold/rpcclient.go

Basically, I tried to do too much planning for the future and fees are currently checked twice which causes manually added tickets to be skipped/ignored.
Closes #207.

skip fee checks on tickets fetched via GetTickets

---

README.md
backend/stakepoold/version.go
glide.lock
glide.yaml
version.go

~~Still doing final testing but this should be it.~~ Testing complete.

glide up, bump version, release notes

---

config.go
controllers/main.go
tplstakepool/readme.md

Just some typos I came across while reading the code...

Fix some typos

---

views/voting.html

views: add link to voting site

---

controllers/main.go

don't leak whether an email is registered or not

---

views/address.html
views/settings.html
views/tickets.html

Close #225 
Paymetheus is deprecated and removed from the downloads section.

Remove references to Paymetheus

---

README.md
backend/stakepoold/server.go

stakepoold: warn rather than err when 0 users

---

backend/stakepoold/userdata/userdata.go

The counter isn't used anywhere AFAICT.

stakepoold: remove dead code

---

controllers/main.go
views/tickets.html

This updates all the links on the tickets page to point to dcrdata.
Resolves https://github.com/decred/dcrstakepool/issues/264

Use mainnet.dcrdata.org instead of mainnet.decred.org

---

backend/stakepoold/rpcclient.go

dcrd v1.4.0 will have the updated RPC version

bump required dcrd JSON RPC version to 5.0.0

---

views/address.html
views/footer.html
views/home.html
views/settings.html
views/tickets.html

Prevent tabnabbing: https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Tabnabbing

views: use noopener noreferrer with blank link target

---

LICENSE
views/auth/signup.html
views/footer.html

Resolving https://github.com/decred/dcrstakepool/issues/296
Also bump dates in footer and license to 2019.

The Sign Up page should not link back to itself.

---

backend/stakepoold/log.go
backend/stakepoold/ntfnhandlers.go
backend/stakepoold/rpc/rpcserver/log.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
controllers/dcrclient.go
controllers/main.go
log.go
server.go
system/core.go
system/middleware.go
system/sigs.go

multi: more error checking

---

controllers/main.go

This checks the return value from `goemail.NewMessage` to avoid a panic in the case of a bad "from" address.
Also check for `SendMail` errors and add a flash message on error.

main: check goemail.NewMessage return value

---

views/auth/signup.html
views/captcha.html
views/passwordreset.html
views/settings.html

Moving 3 duplicated instances of the CAPTCHA form into its own template file so it can be reused.

Remove duplicated captcha html.

---

controllers/main.go
views/address.html
views/footer.html
views/home.html
views/stats.html
views/tickets.html

Also remove a duplicated paragraph from `views/address.html`
Closes #331 
Closes #276

update terminology stakepool => vsp

---

views/admin/tickets.html
views/stats.html

Closes #365
It's not trivial to implement this in pure HTML/CSS, so I have implemented it using a small bit of Javascript. The page is still usable for non-javascript visitors, its just a bit less convenient

allow clicks on any part of row, not just checkbox

---

apiClientExample.sh
controllers/main.go
server.go
views/auth/login.html
views/auth/register.html
views/emailupdate.html
views/emailverify.html
views/home.html
views/main.html
views/passwordupdate.html

The code mixes terminology, signup/register and signin/login.
As the UI has now standardised on register and login, I have updated the code and site URLs to follow the same standard.

standardise signin/login and signup/register

---

public/css/styles.css
views/admin/tickets.html

also make the background of the notifications always white, rather than transparent.
Closes #366

draw notifications on their own row

---

public/css/styles.css
views/tickets.html

Closes #352
@MariaPleshkova  could you take a look a this please?
Preview - see the "Expired" tickets

Show a message when no tickets to display. 

---

views/footer.html
views/home.html
views/tickets.html
views/voting.html

Fixes #376  . Also fixes a minor typo "sode" => "code".

Referrer fix

---

views/tickets.html

tickets: add link to block explorer

---

public/css/styles.css
views/admin/tickets.html
views/tickets.html

Show ticket info with monospace font.

---

views/auth/register.html

dont show registration form when pool is closed.

---

public/css/styles.css
public/js/global.js
views/address.html
views/admin/status.html
views/admin/tickets.html
views/auth/login.html
views/auth/register.html
views/captcha.html
views/passwordreset.html
views/passwordupdate.html
views/settings.html
views/tickets.html
views/voting.html

Close buttons are only displayed if the client enables javascript.
Closes #359

add button to close snackbar notifications.

---

public/css/styles.css

prevent horizontal scrolling

---

public/css/styles.css
views/tickets.html

@MariaPleshkova  could you review this please?
Closes #351

show invalid ticket warning.

---

backend/stakepoold/config.go
backend/stakepoold/rpc/rpcserver/context.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
config.go
config_test.go
controllers/dcrclient.go
controllers/main.go
stakepooldclient/stakepooldclient.go

Left over review comments from #406 
- standardise init of zero values
- organise imports

Minor style fixes

---

public/images/favicon/browserconfig.xml
public/images/favicon/manifest.json

Closes #417 
Also delete an unnecessary file - `.gitkeep` file in unused `/tmp` dir

gui: fix broken image paths.

---

controllers/main.go
views/auth/register.html
views/passwordreset.html

Closes #405 
Marking as a draft while this is thoroughly tested.

Fix confirmation messages for Registration and password reset

---

views/stats.html

stats page: split stats & status into network stats & pool stats

---

views/captcha.html

This fixes the annoying and useless auto suggestion that come up when you try to fill a captcha.

Remove autorefill in the captcha form

---

backend/stakepoold/rpcclient.go

error on incorrect dcrwallet RPC version

---

views/main.html

show user email address rather than placeholder

---

sample-nginx.conf

Seperate nginx config for static files

---

views/emailupdate.html

Email update to same design as passwordupdate. closes #430

emailupdate: emailupdate to same design as passwordupdate

---

controllers/main.go

main.go: get for voting page with no multisig redirects to address

---

views/home.html

Re-add support email address

---

views/stats.html

stats.html: add Block Height to stats page

---

views/passwordreset.html

views: Fix password reset error popup

---

public/js/global.js
views/captcha.html

Disable captcha form when input is empty.

---

email/email.go

Encode a url-friendly password when building smtp url

---

controllers/main.go

Show pool fees on Address page

---

controllers/dcrclient.go
controllers/main.go
stakepooldclient/stakepooldclient.go

This is work on top of #451, I will mark for review once that is merged and any conflicts are resolved.
Contributing to #227

Check wallets are all connected before performing write operations

---

controllers/main.go

controller/main.go: add agenda cache

---

stakepooldclient/stakepooldclient.go

stakepooldclient: more informative errors

---

views/error.html

fix styling of error page

---

controllers/main.go

This should have been removed in #398 Sorry about that.

controller/main.go: remove enableStakepoold field

---

config.go
email/email.go
sample-dcrstakepool.conf
server.go

**Warning**: I lack the infrastructure to properly test this. @dajohi could you please review carefully and if possible run a manual check to confirm that this behaves as expected?
Closes #316 
Closes #341

Add SMTP Cert and SkipVerify configs

---

harness.sh

- Make copies of cert and key files
- Set dcrstakepool SMTP host

Minor harness improvements.

---

public/js/admintickets.js
public/js/index.js
public/js/stats.js
views/admin/tickets.html
views/footer.html
views/home.html
views/stats.html

Remove all in-line JavaScript

---

backend/stakepoold/server.go
backend/stakepoold/server_test.go
controllers/main.go
helpers/address.go
helpers/address_test.go
stakepooldclient/stakepooldclient.go

@jrick says udb should be internal only

multi: drop udb usage

---

sample-nginx.conf

Note version requirement for limit_req delay param

---

README.md

closes #508 
Simplify installation instructions. Remove components section. Be more
explicit with setup instructions.

readme: Simplify and update information

---

views/home.html

Update Profit => Reward

---

public/css/styles.css
views/voting.html

Closes #581 
Changeset on this is actually quite small, but github is going crazy because of whitespace

Always show vote options on /voting

---

server.go
system/core.go

This method doesn't seem to do anything. Removing it. Also using logger
to log errors in server. Log a final message as well.

application: remove Close method

---

views/address.html

Also increase the maximum ticket price because the price is always above 100 these days

Remove unnecessary item from sample config.

---

controllers/main_test.go

Add a test for getClientIP in controllers/main.go

controllers/main: Add getClientIP test

---

server.go
system/core.go

core: Do not use reflect in Routes

---

views/address.html
views/admin/tickets.html
views/footer.html
views/tickets.html
views/voting.html

Open external links in a new tab

---

backend/stakepoold/config.go
backend/stakepoold/server.go
config.go
helpers/address_test.go
server.go
system/sqlstore.go

multi: use std errors package

---

controllers/main.go
controllers/main_test.go
server.go
stakepooldclient/stakepooldclient.go

In order to facilitate testing, change Config's StakepooldServers to an
interface that stakepooldManager satisfies and contruct a test manager
to be used in this test and others.

controllers/main: Add NewMainControllerTest 

---

controllers/main.go
controllers/main_test.go
go.mod
go.sum

To facilitate testing, change agendas to accept an optional function
that takes the place of dcrDataAgendas.
Return a pointer to agendas rather than making a copy.

controllers/main: Add agendas test

---

models/user.go
server.go
system/core.go

system: change Init to a func that returns an Application

models: change GetDbMap to return an error
