decred/dcrstakepool

.gitignore
config.go
controllers/dcrclient.go
controllers/main.go
glide.yaml
helpers/auth.go
models/user.go
system/core.go
views/tickets.html

Remaking https://github.com/decred/dcrstakepool/pull/32 after new repo was created.  Original un-squashed branch [here](https://github.com/chappjc/dcrstakepool/tree/votebitssync).
This implements vote bits (re)synchronization/repair.  Please test and review.  All of the new or modified functionality is tested on a testnet pool, but there may be more attack protections that should be made (walletRPCHandlerize any of this?).
In terms of behavior:
- On startup of dcrstakepool, a full vote bits sync of all tickets owned by the pool is performed.  It will be skipped if importscript gets run since that takes a long time.
- /tickets POST (set bits) has a short timeout so a large number of tickets does not block page loading.
- A flash message will indicate that a tickets sync is in progress.  No …

Vote bits sync.

---

controllers/dcrclient.go
controllers/main.go

More logging around startup sync, which can feel like it's hung for lots of tickets, and the POST handlers.
The calls to `GetTickets` are particularly slow, so it's helpful to have these messages:
```
08:11:00 2016-11-12 [INF] DCRS: Established connection to RPC server ...:...
08:11:00 2016-11-12 [INF] DCRS: Getting address index and importscript information from wallets.
08:11:01 2016-11-12 [INF] DCRS: Syncing wallets' redeem scripts and setting address indexes.
08:11:04 2016-11-12 [INF] DCRS: SyncVoteBits: Getting list of all live tickets on wallet 0.
08:12:09 2016-11-12 [INF] DCRS: SyncVoteBits: Excluding 0 unmined tickets in votebits sync.
08:12:09 2016-11-12 [INF] DCRS: SyncVoteBits: Checking number of tickets on wallet 1
...
08:14:29 2016-11-12 [INF] DCRS: Beginning resync of vote …
```

More sync and POST logging

---

controllers/dcrclient.go
glide.lock
glide.yaml

Something went missing from https://github.com/decred/dcrstakepool/pull/60, as I mentioned [here](https://github.com/decred/dcrstakepool/pull/60#issuecomment-260112267).  After multiple rebases, something got lost or this was simply waiting on dcrrpcclient updates that took too long.  Unfortunately, master builds just fine, but the handler for the message of the added type was just not there.  This PR adds the missing pieces.
Also, as mentioned in the TODO for https://github.com/decred/dcrstakepool/pull/61, the start-up sync could stand to be sped-up.
The glide.lock had to be updated, but glide up wasn't doing it unless I wiped the glide cache, which unfortunately updated all the third party stuff too.

Finish SetTicketsVoteBits handling, update glide.

---

config.go
controllers/dcrclient.go
controllers/main.go
server.go

Since getMinedTickets was added, which removes unconfirmed tx from list from GetTickets, it's OK now to use getstakeinfo.(Live + Immature) to compare the total live (actually live+immature) ticket count on the other wallets with the count from getMinedTickets(gettickets(true)).
This makes startup much quicker and far less likely to hit a non-equiv error that you would get when live count goes down during startup.
Tested on testnet with and without unconfirmed tickets during startup (only time this is run).

Speed up startup live ticket count check in SyncVoteBits

---

server.go

Following up on PR https://github.com/decred/dcrstakepool/pull/67.
There's a need to flush the log backend before os.Exit().  Do like other projects and wrap main() so deferred functions get run.
Try using `--listen=[wrongIP]:8000` and you get no messages, it just exits.  You should see:  `could not bind listen tcp [wrongIP]:8000: bind: cannot assign requested address`

Flush log before exit and wrap main().

---

controllers/main.go
poolapi/apijson.go
server.go
system/core.go

Trying PR https://github.com/decred/dcrstakepool/pull/69 again.
**UPDATED: Pretty well tested**, but needs more documentation.
I believe the API needs several improvements, but this pertains to the following:
- For the convenience of encoding JSON by the server, struct response types with json tags should be created.
- For Go clients the json structs should put in their own package.
- The main API handler should be rewritten to use these types and the encodings/json package.
- The route handler should not include logic for parsing the version and command out of the url (goji and any router will do that).
Specifically, from the commit messages, this PR does the following:
- Add `poolapi` package with json structs, and new+modified api routes.  The `poolapi` package helps write go clients, …

	Add poolapi package with json structs, new api routes.

---

controllers/main.go
glide.lock
glide.yaml
helpers/auth.go
models/user.go
system/controller.go
system/core.go
system/middleware.go

Dependencies in gopkg.in seem to be broken with glide:
```
[INFO]    --> Fetching gopkg.in/gorp.v1
[WARN]    Unable to checkout gopkg.in/gorp.v1
[ERROR]    Update failed for gopkg.in/gorp.v1: Unable to get repository
[ERROR]    Failed to install: Unable to get repository
```
This switches to the referenced version in github.com.

Move gorp dependency from gopkg.in to github.com.

---

controllers/dcrclient.go
controllers/main.go

Closes #108.
Related to #99.
Basically where we're at now:
- dcrwallet 0.8.2 has deprecated enablestakemining
- dcrd master has various walletinfo fields removed
- dcrwallet has a pr pending to update the walletinfo rpcs
- We're moving to a voting daemon for 1.0 rather than having the wallet vote directly.
So with all that being taken into account, I think it's best to just remove the stakemining safety check.  The pools are well established now so hopefully it won't cause an issue to remove this minimal safety check.

remove deprecated fields and disable stakemining safety check

---

config.go
controllers/main.go
sample-dcrstakepool.conf
server.go

Closes https://github.com/decred/dcrstakepool/issues/84
go fmt also alphabetized imports
NOT yet tested.

Use net.SplitHostPort instead of string splitting.

---

config.go
controllers/main.go
glide.lock
params.go

Closing the pool should only prevent new signups, but presently it prevents registered users from logging in and uploading their address.
Remove the close pool checks from the API address handler, the /address POST handler, and the signin POST handler.
SignUp is still restricted when closePool is true.
Work in progress in that I will update when done testing.
Closes #114.

Always allow registered users to login and submit their address

---

controllers/dcrclient.go
controllers/main.go

Make travis happy/happier by addressing gosimple issues.
- It is unnecessary to specify both the size and capacity of a slice when they are equal values.
- Document ErrSetVoteBitsCoolDown and NewGetTicketsCacheData.

gosimple and other lint fixes

---

views/stats.html

This was probably conditional because there were pools with
wallets that did not yet break out expired, and would have been
wrong to show this value as 0 in those cases.  However, all pools
should support the expired value from getstakeinfo.
When .StakeInfo.Expired is 0, it would have been hidden.  This fixes that.  If your wallet doesn't have it, you don't meet the requirements to run dcrstakepool.

Always show the expired count in the stats page

---

controllers/main.go
controllers/main_test.go

This is a fix for the /tickets page, which generates block explorer links using the "Network" env value, set by this network string (there is no testnet2.deced.org).
Also add tests.

Add getNetworkName method to strip suffix off testnetN network names

---

backend/stakepoold/server.go

In order to see early errors we need the defer to backend flush to be
setup much earlier.  This enables us to see errors before the daemon
comes online.

Move defer to proper location.

---

backend/stakepoold/server.go
backend/stakepoold/server_test.go

`deriveChildAddresses` takes a start index and a count, not a [start, end) range.
Add server_test.go, and test for `calculateFeeAddresses` using a testnet extended public key.

backend: Fix computing 1 extra fee address, add test

---

backend/stakepoold/rpcclient.go

Only perform map lookup once in `walletCreateVote`.  Verify that the multisig address was found in the map.

simplify send/create vote functions in backend rpcclient

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
backend/stakepoold/server_test.go

As a quick workaround we held locks longer than needed.  It is time to start moving this code to hold locks only on data.  There is much more cleaning to be done but this is where we start.

stakepoold: only lock data, not code path

---

config.go

Now all stakepoold config validation is properly wrapped behind
```go
if cfg.EnableStakepoold {
```

move stakepoold certs/hosts checks into proper place

---

backend/stakepoold/server.go
backend/stakepoold/server_test.go

Benchmark was broken because appContext.votingConfig was nil.  So fix is to set a valid VotingConfig when creating the appContext in init() in server_test.go.
For a more realistic benchmark, also fill out the userVotingConfig map.  Previously it was empty, and the lookup would fail, and default voting config was used.  By adding random user multisigs, where the last 5 own the winning tickets.
Reorder fields of VotingConfig so it goes from 40 -> 32 bytes by avoiding excess padding.
Remove unnecessary allocation of a UserVotingConfig inside processWinningTickets (when msa lookup fails).
Simplify timing of processWinningTickets by using time.Since.

Fix processWinningTickets benchmark

---

README.md

Belated update of the upgrade guide/release notes.  Tried to clean things up and clarify the status of mainnet vs. testnet w/stakepoold as much as possible.
Let me know if anything was neglected or needs improvement.
@chappjc @girino @karamble @jyap808 @mverrilli @dyrk @Retord @walkeralencar @tpruvot

improve upgrade notes for 1.1.0

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go

Try to cram as much work as quickly as possible into the network services.  The idea here is to have as much data travel at the same point over slow networks by doing a bit more processing up front in the daemon.  This seems to bring the overall voting latency to the sub 10ms range.

stakepoold: use go routines to stack network communication

---

backend/stakepoold/config.go
backend/stakepoold/server.go

This certainly would not be a recommended mode of operation, but with the current model of stakepoold connecting directly to MySQL for user voting configuration, it's possible to run an extra pool wallet without changing dcrstakepool config, while honoring user voting prefs.
The idea here is to reload every N minutes from MySQL if the `--norpclisten` flag is set.  This will also prevent the gRPC server from starting.
The first commit splits the timing of `vote()` into sign, send, and total.  This is unrelated to the gRPC change.
I'm pretty sure merging this is not the right idea, but I wanted to put it out there because it provides a quick way to fire up another wallet that will vote as desired without messing with the main server much, if at all.
Note there is also a doc correction in …

Add option to run stakepoold without gRPC server

---

controllers/main.go

Reported by jyap on slack:
```
08:00:07 2017-06-12 [INF] CNTL: updated voteBits for user 249 from 1 to 19
08:00:08 2017-06-12 [INF] CNTL: updated voteBits for user 249 from 19 to 19
08:00:13 2017-06-12 [INF] CNTL: updated voteBits for user 249 from 19 to 19
08:00:16 2017-06-12 [INF] CNTL: updated voteBits for user 249 from 19 to 19
08:00:38 2017-06-12 [INF] CNTL: Multisigaddress empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8d4f36]
goroutine 172 [running]:
github.com/decred/dcrstakepool/vendor/github.com/decred/dcrrpcclient.(*Client).StakePoolUserInfoAsync(0xc4200d9540, 0x0, 0x0, 0xc4206741a0)
//gopath/src/github.com/decred/dcrstakepool/vendor/github.com/decred/dcrrpcclient/wallet.go:3243 +0x26 …
```

Do not ignore invalid or missing P2SH multisig on /tickets

---

config.go
controllers/dcrclient.go
controllers/main.go
controllers/main_go18_test.go
controllers/main_test.go
sample-dcrstakepool.conf
server.go
views/tickets.html

Aims to address, in part, issue https://github.com/decred/dcrstakepool/issues/56
Reduced scope of this PR:
Possible goals for follow-up changes:
- Cache live tickets, but not voted. For each user.  Memory is not a constraint for millions of tickets, and CPU will not be either as the users will be in their own buckets.
- Put voted tickets on a separate page: (a) all voted on separate page and none on main tickets page, or (b)  all on the other page and with the most recent on main tickets page.
- To do (b) in the previous, cache the most recent voted tickets for each user.
- Allow downloading a CSV (or whatever) list of historical tickets.
- Maintaining the live/voted/etc tickets caches intelligently (i.e. without simply regenerating the lists if X minutes have passed) is desirable but not …

Accelerate tickets page

---

backend/stakepoold/log.go
backend/stakepoold/server.go
glide.lock
log.go

This update adds additional callsite logging options via btclog and
fixes an error with the rotator package that caused it to stop running
when creating any log messages larger than 4096 bytes.
While here, switch to the new Write method of the Rotator object as
this is more efficient than using the Reader interface with a pipe.
Fixes #192.

Update deps to pull in additional logging changes.

---

views/address.html
views/tickets.html

Mention that the generated multisigscript depends on both wallets and tell them to talk to the pool admin/support staff if they need to change it.
Closes #195.
Some other minor stuff:
- Point to voting docs in case they want to self-vote with the CLI wallet.
- Update example price to be more realistic.
- No longer explicitly recommend auto-ticketbuying over manual now that the ticket pricing algorithm is more sane.

mention wallet/script dependency and voting docs

---

backend/stakepoold/grpcserver.go
backend/stakepoold/ntfnhandlers.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
backend/stakepoold/server_test.go
backend/stakepoold/version.go
sample-stakepoold.conf

This reworks the ticket handling of stakepoold.
Previously, it would do stakepooluserinfo for every user on startup and every block thereafter.
This switches it to use gettickets on startup and then add/remove tickets based on the OnNewTickets / OnSpentAndMissedTickets notifications.
stakepoold's ticket count now stays in sync with the live ticket count from getstakeinfo.
This also adds caching so voting can resume immediately.
Closes #177.
Closes #179.

stakepoold: Fix ticket handling to be more accurate.

---

backend/stakepoold/ntfnhandlers.go
backend/stakepoold/server.go

We went back and forth in #178 on different ways to implement prioritize handling of the winning tickets notification/voting over the other notifications.
As we can see from #211, a waitgroup is not the right solution. It essentially makes us stateful but that doesn't work since dcrwallet may send us 0 or 2 voting notifications, rather than the 1 we expect to get 99.9% of the time.
~~Opened for discussion. This is a WIP (mostly because I haven't tested it yet)~~
Closes #211.

remove voting prioritization

---

run_tests.sh

Just to make sure we catch typos before committing ;)
[References #222]

Enable misspell when running gometalinter

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go

If stakepoold starts while dcrd RPC is inactive, it will fail to get any
tickets but will continue to start nonetheless. Therefore it won't watch
for any tickets and this will lead to missed votes.
This commit ensures that stakepoold won't silently ignore this error. It
is recommended to use a process supervisor to keep restarting stakepoold
until the RPC is ready.
---
Log snippet of the issue (note the `result null` which should be an array of ticket hashes):
```
[INF] STPK: Calling GetTickets...
[TRC] RPCC: Sending command [gettickets] with id 3
[TRC] RPCC: Received response for id 3 (result null)
[INF] STPK: GetTickets: took 1.014074ms
[WRN] STPK: GetTickets failed: -1: Chain RPC is inactive
```

Abort stakepoold startup if cannot get tickets

---

controllers/main.go

`Env["User"]` is already set globally by the [ApplyAuth](https://github.com/decred/dcrstakepool/blob/1a3c844122667b585d42479e7da48ea68145450b/system/middleware.go#L96) middleware.

Remove superfluous assignment

---

.travis.yml
Gopkg.lock
Gopkg.toml
backend/stakepoold/grpcserver.go
run_tests.sh

This fixes the travis environment so it runs the Go 1.8 tests properly.  GOVERSION wasn't being set in the environment so travis was testing Go 1.9 twice.
It also bumps the gRPC version to a supported stable release and adds an context import workaround for the issue described in #238.
Fixes #238.
Supersedes #239.

travis: sync with dcrd's run_tests.sh and fix 1.8

---

backend/stakepoold/config.go

Now we use the defaultHomeDir to create dir, it could failed when user change the home dir to another.

config: use cfg.HomeDir to replace defaultHomeDir

---

backend/stakepoold/rpcclient.go
backend/stakepoold/server.go

Wallet legacy RPC version was bumped from 4.1.0 to 5.0.0 in dcrwallet commit: https://github.com/decred/dcrwallet/commit/c1da68c40d2d4260beca96e8ed75cc91cfa0d0ce
(sendtosstx was removed, and this was not used by dcrstakepool/stakepoold)
Also fix some incorrect logging messages.

Bump wallet RPC API version to 5.0.0

---

LICENSE
README.md

This project contains code governed by the MIT/X11 and ISC licenses.
The ISC license and copyrights have been added to the LICENSE file in
the root of the project, and the README has been updated to reflect
the current licensing.

Correct licensing

---

views/tickets.html

dcrwallet version 1.1.2+release (Go version go1.9.2)
--ticketaddress=                         DEPRECATED -- use ticketbuyer.votingaddress instead

change ticketaddress to ticketbuyer.votingaddress

---

README.md

Remove dep instructions and describe Go module builds.
Lots of linting and formatting.
Resolves https://github.com/decred/dcrstakepool/issues/278

readme: update build instructions for modules.

---

backend/stakepoold/server.go

The error string created by the dcrwallet JSON-RPC gettransaction when a
transaction is not found changed in the 1.3.0 release.  This change modifies
stakepoold to repress the newly-formatted errors from being logged.
While here, include a gofmt fix from Go 1.11.

Repress logs for unfound ticket lookups.

---

config.go
controllers/captcha.go
controllers/main.go
go.mod
go.sum
sample-dcrstakepool.conf
server.go
system/controller.go
system/core.go
system/middleware.go
views/auth/signup.html
views/footer.html
views/passwordreset.html
views/settings.html

This replaces Google's reCAPTCHA with a self hosted captcha.
**NOTE**:  This is needs review and testing.  It works for me though.
Create controllers/captcha.go, where the captcha GET and POST handlers
are implemented for retrieving images and verifying responses.
Create `CaptchaHandler` type with image size spec, and add it as a field
of `MainController`.
Create `ApplyCaptcha` captcha middleware.
Add GET route for `/captchas` for serving the captcha images.
Add POST route for `/verifyhuman` for verifying captcha responses and
redirecting to the previous page with the session updated.
Modify http handlers to display new captcha: `PasswordReset`, `SignUp`, and
`Settings`.
Modify http handlers to check for captcha verification:
`PasswordResetPost`, `SignUpPost`, and `SettingsPost`. …

replace recaptcha with self-hosted captcha

---

backend/stakepoold/config.go
config.go
go.mod
go.sum

This mirrors the code in other Decred repositories such as `dcrd` and `dcrwallet`.

deps: Update to use upstream go-flags.

---

controllers/main.go

The sprintf that was here would result in a string that assumes a blank user and password. smtp://:@host  This can cause an issue for local email relay if password is not required, yet net/smtp will receive a blank password from the parsed url.

SMTP should not require user/pass auth

---

controllers/dcrclient.go
controllers/main.go

The only scripts that are imported by the controller are ones that were just
created from a createmultisig RPC, and should not have any history that requires
a rescan to find previous outputs.  Remove the rescan request from the
importscript parameters to prevent the wallet (which no longer serializes and
batches rescan jobs) to prevent extraneous resource usage for unnecessary
rescans.

controller: Never rescan during script imports

---

system/core.go

Adds ` "Cache-Control", "private,no-store,no-cache"` to html responses, this will fix #318

Adds a Cache-Control header to stop sensitive data from being cached

---

helpers/auth.go

Fixes #320 
This will delete all reset tokens of user when their email gets changed.

Delete password reset tokens on email change

---

config.go
controllers/main.go
email/email.go
sample-dcrstakepool.conf
server.go

- Add new config item to enable smtps
- Move email templates and code into dedicated file.
- Dont start dcrstakepool if the smtpfrom email in config is invalid. This prevents errors occuring later.
- Remove some unnecessary new lines from email templates.
Closes #327

email refactoring.

---

controllers/main.go
go.mod
go.sum
sample-dcrstakepool.conf
server.go
system/controller.go
system/core.go
system/middleware.go
views/address.html
views/admin/tickets.html
views/auth/signin.html
views/auth/signup.html
views/captcha.html
views/passwordreset.html
views/passwordupdate.html
views/settings.html
views/voting.html

Replace custom implementation of CSRF with [gorilla/csrf](https://github.com/gorilla/csrf).
- Reuse the existing config item "apisecret" to generate CSRF tokens.
- In `core.go`, dont attempt to save a session in the API handler because API requests do not utilize sessions.
- Make use of "route groups" so that not all middlewares have to run against all routes. This simplifies existing middleware, and allows us to apply CSRF to only html routes and not API routes.
Closes #309

server: use gorilla for csrf

---

controllers/main.go
views/captcha.html

The error messages are not being displayed at the moment. The captcha is simply reloaded and no feedback is given to the user

show error message for failed captcha

---

backend/stakepoold/grpcserver.go
backend/stakepoold/ntfnhandlers.go
backend/stakepoold/rpc/rpcserver/context.go
backend/stakepoold/rpc/rpcserver/server.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
backend/stakepoold/server_test.go

In order to add a new RPC call to stakepoold in #342, it was necessary to add a lot of nasty code to `stakepoold/rpc/rpcserver/server.go`, and this really should not be needed. This PR removes that nasty code, and thus makes it easier to add/change stakepoold RPC calls in future (eg whilst implementing #227).
The changeset is quite big, so I have broken it into two commits:
1. The first commit simply moves/renames existing code without making any significant changes. It splits the `appContext` code out of `stakepoold/server.go` and into its own, reusable, file `stakepoold/rpc/rpcserver/context.go`
2. The second commit passes the AppContext instance into `stakepoold/rpc/rpcserver/server.go` which allows the nasty code to be removed from that file.
The stakepoold code after this PR is still …

Tidy up RPC server

---

controllers/main.go
server.go
stakepooldclient/stakepooldclient.go

The method `StakepooldUpdateAll` could either update users, tickets, or both. The behaviour was controlled by a flag parameter, and this resulted in overly complex code which is difficult to modify. This PR splits the single complex method into two simple ones: `StakepooldUpdateTickets` and `StakepooldUpdateUsers`.

simplify overly complex method

---

controllers/main.go

This will reset the the captcha to "false" after each sensitive request.
fixes #343

Reset captcha value

---

controllers/main.go
server.go
stakepooldclient/stakepooldclient.go
views/admin/status.html

`dcrstakepool` connects to multiple instances of `stakepoold` and `dcrwallet` over gRPC. The code managing the `dcrwallet` gRPC connections is significantly more robust than the `stakepoold` counterpart.
`dcrwallet` connections are managed in a single place - namely [dcrclient.go](https://github.com/decred/dcrstakepool/blob/master/controllers/dcrclient.go). This file is responsible for comms to the multiple `dcrwallet` connections, error handling, retrying etc. Management of `stakepoold` connections is scattered throughout the code.
This PR introduces a connection manager for the stakepoold connections, similar to what exists for dcrwallet. Making stakepoold connection management more robust will become important in the future as we take further steps towards #227 and the `dcrwallet` …

introduce stakepoold connection manager

---

server.go

if at first you don't succeed...
change runMain() in server.go to run errors
this may cause some errors to be printed twice

Clean Up: runMain() in server.go to return error

---

controllers/main.go
views/error.html

Fixes #378 
This removes `c.Env["Referer"]` and `error.html` will no longer offer a redirect link.

Remove referrer parameter from error page

---

config.go
config_test.go
controllers/main.go
server.go

part of issue #226 
Move validation of pubkeys, length and network, to config.
I made the parsed keys into package level variables because it felt weird to include them in the config struct since they are not configured by the user.

Clean Up: move pubkey parsing to config

---

config.go
controllers/main.go
sample-dcrstakepool.conf
server.go

part of issue #226 
remove ability to disable stakepoold communications.
After making these changes, the user will need to remove the "enablestakepoold=" option from their config or see an error during parsing
This will cause merge conflicts with another of my pull requests...

remove enable stake pool as an option, always enabled

---

config.go
controllers/dcrclient.go
controllers/main.go
sample-dcrstakepool.conf
server.go

Rendering the `/tickets` page with a huge number of tickets results in the page loading very slowly.
|No. Tickets|Page Load (ms)|
|---|---|
|10|180|
|100|250|
|500|420|
|1000|600|
|2500|1300|
|5000|2200|
|10000|5000|
|17500|9600|
|25000|14900|
|37500|25200|
|50000|39000|
We currently mitigate this issue by only rendering the page with tickets which have voted in the last N blocks. This is not ideal for various reasons:
- The default for N is 8064, which means that in the worst possible case the page is rendered with 40,320 tickets. This means a page load of around 30 seconds.
- We need to call dcrwallet RPC to find the current best block
- A user may only have a single voted ticket, but if that ticket voted more than N blocks ago, it wont be displayed on the page.
I propose that we switch …

Show last N voted tickets

---

backend/stakepoold/rpcclient.go
controllers/main.go
views/tickets.html

tickets page: distinguish between live and immature

---

controllers/main.go
controllers/main_test.go
views/tickets.html

Closes #353 
- Ticket lists were being displayed in reverse order so I have reversed the sorting.
- Only the oldest 1000 voted tickets were being displayed rather than the most recent 1000. That has been fixed.
- Now also showing each ticket's purchased/voted/revoked height.

 Notify when not all voted tickets are displayed

---

system/middleware.go

Setting interface value to nil does not remove it as a map item.
This check is nearly always true as we often set session.Values["UserId"] = nil in the code, but this does not remove the interface from the map.  you can see this behaviour demonstrated here https://play.golang.org/p/WfodUJh2U6u
I believe the intent of this function was not to fire if there is no user id.  Right now it is searching for nothing anyway when there is no user id.

middleware: bad check

---

email/email.go
views/address.html

Also add a missing space to one of the email templates.
Closes #426

Update advice for connecting a new wallet.

---

controllers/main.go
public/css/styles.css
views/address.html
views/tickets.html

- Moved "i" icon which explains the submitted public key address. It is now found next to the pubkey, rather than next to the page header.
- Always show Decrediton API key (Closes #416)
- Moved "Ticket Information" section from the Tickets page into the Connect to Wallet page (Closes #415)
- Remove duplicate code which validates addresses submitted through the Connect to Wallet page
I suggest reviewing with "Ignore whitespace changes"

Rework "Connect to Wallet" Page

---

public/js/global.js
views/admin/tickets.html
views/stats.html

This PR standardises the approach of hiding page elements when Javascript is not available, removing some duplicated code.
I started this work with the intention of implementing #354, however the code provided in the design spec is not suitable for production use. It has simply been written as a demonstration of the intended functionality, therefore this would need to be implemented from scratch and a lot of the existing code would need to be reworked to accommodate it.
As #354 is only a minor cosmetic change, it seems like more effort and added complexity than it is worth, therefore I am going to say this PR Closes #354.

Remove duplicated js-only code

---

server.go

check url for gets directed at "/assets" and "/captchas" and ignore them
in the middleware
before this change, open home, fmt.Println("ApplyDbMap") in middleware.go func ApplyDbMap
after this change, open home with the same print in the same place
I don't believe middleware should be applied to gets to pics for performance reasons, as they aren't using the information, I don't think

middleware: don't use middleware when loading images

---

README.md
backend/stakepoold/rpc/stakepoolrpc/api.pb.go
go.mod
go.sum

This updates the golang protobuff package to use version 3
https://github.com/golang/protobuf/releases
When I first tried to use the .regen script to make our api.pb.go I was confused by the created go file having the constant const _ = proto.ProtoPackageIsVersion3 and finally found the answer to be downgrading my golang protoc version to v1.2.0. I believe we discussed this @jholdstock ?  
This pr will allow us to use the latest protoc.  I have compiled and bought some tickets with this, without updating stakepoold, and it seems to be going fine.  I will test some more to make sure there are no problems with updating this.

go.mod: update to protogen version 3

---

backend/stakepoold/rpc/rpcserver/server.go
stakepooldclient/stakepooldclient.go

This is an overdue change. The API version should have been incremented when new calls were added for #227

rpc: increment api version

---

controllers/main.go
go.mod
go.sum
models/user.go
system/core.go
system/middleware.go
system/sqlstore.go
system/sqlstore_test.go

This PR Creates a new column in the dbo to hold a token which is used to monitor password changes and nullify the session if the password was reset from anywhere else. It also adds a timeout of one day to idle sessions (too long?).
You can test the code here https://test.dcrstakedinner.com/
If you make an account, the emails will probably go to your junk folder
A couple questions, should there be a page or alert to inform a user that their session has ended? And, I'm doing something kind of funky in the middleware so that checks don't fire for loading images and captcha. Without this check the middleware fires multiple times per page load. perhaps this is not wanted behaviour and should be handled in another pr?
closes #328, closes #235, closes #379

multi: new sql store and session nullification on password change and logout

---

views/captcha.html

Implements client side input validation for captcha.
I earlier thought we make `type="number"` but discovered that it does not allow for length validation.

Implement client side input validation for captcha

---

views/tickets.html

Purchase height is not available for invalid tickets, so should not attempt to display it
Closes #460

Do not attempt to display Invalid ticket height

---

controllers/main.go
stakepooldclient/stakepooldclient.go
views/admin/status.html

dcrstakepool will soon have no RPC connections directly to dcrwallet, so this PR simplifies the `/status` page to display stakepoold connections only. Also adds the wallet vote version which was not previously visible.
Needed for #227

Remove dcrwallet RPC from status page

---

README.md
harness.sh

See changes in `README.MD` for further info

add tmux test harness

---

.gitignore
README.md
config.go
sample-dcrstakepool.conf
server.go

- Use `config.MinServers` parameter to check the number of required dcrwallet and dcrstakepoold instances.
- Readme says `SMTPHost now defaults to an empty string so a voting service can be used for development or testing purposes without a configured mail server.`
This doesn't work currently, producing the error message instead: `Failed to initialize the smtp server: invalid smtpfrom address ""`. Support for empty `smpthost` config value is implemented in this PR.

dcrstakepool: correct dcrwallet/stakepoold count check, allow empty smtphost configuration

---

harness.sh
public/css/styles.css
stakepooldclient/stakepooldclient.go
views/admin/status.html

- Use colors to indicate incorrect values which need attention
- Show the hostname and port rather than just an index
- Show a proper message when WalletInfo is not available, rather than just showing the zero value for each column.
Also bundled in some minor refactoring for the test harness.

Status page improvements

---

stakepooldclient/stakepooldclient.go

This was an oversight on my part. An error should continue with the loop.

stakepooldclient: continue loop on error

---

controllers/main.go

If all of the stakepoold servers are down, the comment on the error suggests that the user will see a message about trying again, but as it was written, all they see is `internal server error`. This redirects to the default error page which does have a message saying to try again.

controllers/main.go: tickets rpc error page

---

backend/stakepoold/rpc/rpcserver/server.go

Check whether the wallet is connected before sending rpc commands.
part of #475 
Perhaps this is the easiest solution. It's solving the original problem that I described in that issue. Simply check that the wallet is connected before continuing to send rpc commands.  Another solution I suggested was to write our own reconnect function, but maybe that's not necessary to solve this problem.

rpcserver: Add walletConnected method

---

backend/stakepoold/ntfnhandlers.go
backend/stakepoold/rpc/rpcserver/client.go
backend/stakepoold/rpc/rpcserver/context.go
backend/stakepoold/rpc/rpcserver/server.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go

Turn off rpcclient's autoreconnect and use our own.  This is done to remove the checks before ever wallet rpc call.  Checks for a disconnect every so often and starts trying to reconnect.

Autoreconnect

---

backend/stakepoold/rpc/rpcserver/context.go
backend/stakepoold/rpcclient.go

The low fee tickets feature has been broken since inception.
There are multiple places where tickets are validated and
they had inconsistent error handling.
This PR also includes some logging and commenting I added
whilst investigating the issue.
Closes #521

Ensure low fee tickets are detected upon maturation.

---

go.mod
harness.sh
system/core.go
views/stats.html

Previously, `template.Must(httpTemplates, nil)` was pointless (`err=nil`).
This assigns the parsed templates directly to the `Templates` field.
Also define a template function map for more involved template tasks.
e.g. On the stats page, use the `netname` function for links. This could
also be done prior to executing the template, but it may be desirable
to have the actual network name with any number suffix (e.g. testnet3)
still available in the `Network` data field.
Add `debuglevel=debug` to the stakepoold and dcrstakepool config used
in harness.sh.

clean up LoadTemplates and link to explorer on stats page

---

backend/stakepoold/server.go
controllers/main.go
sample-dcrwallet.conf

~-make max users a configurable variable~
~-default 10000~
~-stakepoold start with default 10000~
~-when starting dcrstakepool grpc commands are used to set the max on all servers and re-derive pool fees if there was a change~
~ahh, meant to do the draft thing, adding WIP to title~
This pr took a different direction mid-stream.  I now think that maxusers is an artificial ceiling and it should be removed. If my understanding is incorrect, please comment.

maxusers: Update TODOs

---

backend/stakepoold/rpc/rpcserver/client.go
backend/stakepoold/rpc/rpcserver/context.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
backend/stakepoold/signal.go

A struct channel was used in order to signal shutdowns. This changes
that to a context.Context that we can spawn new contexts from. Abstracts
the task to a seperate file signal.go
This is pretty much a copy/paste from dcrd and dcrwallet.  This gives us a base context to spawn new contexts off of.
One difference is that the name "ctx" is taken. Can we rename all "ctx" to something else?
Also, no idea what to do with the copyrights. Help me out.

stakepoold: Add shutdown context

---

controllers/main.go
system/core.go
views/admin/tickets.html
views/stats.html
views/tickets.html

The dcrdata URL is now only built in one location rather than scattered
throughout the templates.

Simplify construction of dcrdata urls

---

backend/stakepoold/grpcserver.go
backend/stakepoold/log.go
backend/stakepoold/ntfnhandlers.go
backend/stakepoold/rpc/rpcserver/server.go
backend/stakepoold/rpcclient.go
backend/stakepoold/server.go
backend/stakepoold/server_test.go
backend/stakepoold/signal.go
backend/stakepoold/stakepool/client.go
backend/stakepoold/stakepool/log.go
backend/stakepoold/stakepool/stakepool.go
go.mod
go.sum

I do not think that context.go belongs in the rpc package.  If it were just relaying rpc commands, sure, but it does and will do more.  The name "context" also conflicts with context.Context, which we want to start using to pass shutdowns and "request-scoped values across API boundaries and between processes"
This pr moves context to its own package named stakepool, renames the main struct Stakepool, and renames all references to it stakepool.
this work is on top of #528

stakepoold: context -> stakepool

---

go.mod
go.sum
params.go

I don't think we are using or plan to use the wallet rpc port anymore for dcrstakepool as all wallet communication will pass through stakepoold.

params: Remove unused WalletRPCServerPort

---

backend/stakepoold/grpcserver.go
backend/stakepoold/log.go
backend/stakepoold/rpc/server/log.go
backend/stakepoold/rpc/server/server.go

depends on #529 
Suggested by @jholdstock to use the nameing convention:
rpc/server
rpc/client
This moves rpc/rpcserver -> rpc/server as the second rpc is redundant
The current stakepool/client.go file is a wrapper and will be removed asap. I don't think it's worth the trouble to move it now tbh. I will if someone thinks otherwise though.

stakepoold: Move rpc/rpcserver to rpc/server

---

internal/version/version.go

Closes #556 
The next tag will be v1.5.0.

bump version to 1.5.0-pre.

---

public/css/styles.css

Closes #555
Previously a border was appearing upon hover and pushing other content around the page.
Now the border is always there, but it is transparent until it is hovered over.

Prevent header links from moving

---

backend/stakepoold/stakepool/stakepool.go
backend/stakepoold/userdata/userdata.go
controllers/api.go
controllers/captcha.go
controllers/main.go
email/email.go
helpers/auth.go
helpers/template.go
models/user.go
poolapi/apijson.go
server.go
stakepooldclient/stakepooldclient.go
system/controller.go
system/core.go
system/middleware.go
system/sigs_unix.go
system/sqlstore.go
system/sqlstore_test.go

Closes #564 
Unexport one method. Change all occurrences of Id as a field with ID.
Changing the Id fields to ID isn't actually necessary to get the score down. So let me know if anyone disagrees with that.  I think it is more uniformed this way. However, the fields in the db are already mostly "somethingId" so...
https://goreportcard.com/report/github.com/JoeGruffins/dcrstakepool
I haven't touched the gocyclo. If that's something that should be worried about we can make a new issue.

multi: Comment all exported functions.

---

server.go

There is a chance that logging has not been initiated yet, causing a
panic.
I changed this in #588 but it was a mistake. You can see the panic on master by passing the -h or -l flag.

Print startup error to os.Stderr

---

config.go
log.go

avoid nil deref panic if logrotator is not initialized.

dcrstakepool: exit early on configuration error.

---

controllers/main.go
controllers/main_test.go
server.go
stakepooldclient/stakepooldclient.go

Instead of always using a new context, just pass around the running context
or use the http request context.

Add contexts

---

backend/stakepoold/stakepool/stakepool.go

This allows stakepoold to function when deploying dcrwallet v1.6.x.

Replace addticket with addtransaction
